build site:
  image: node:10
  stage: build
  script:
    - yarn install 
    - yarn build

  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:10
  stage: test
  script:
    - yarn install 
    - npm run test

    # image: docker
    # services:
    #   - docker:dind
    # stages:
    #   - deploy
    # step-deploy-prod:
    #   stage: deploy
    #   script:
    #     - docker build -t app/vue-demo .
    #     - docker run -d -p 80:80 --rm --name vuetify-material-dashboard app/vue-demo

