image: python:3.6

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'ubuntu'
       MYSQL_PASSWORD: ''
       MYSQL_ROOT_PASSWORD: ''
web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - test

before_script:
  - python -V                                   # Print out python version for debugging
  - pip install -r requirements.txt

Build:
  stage: build
  script:
    - python manage.py test --pattern="sign_in.py"
    


  
