build site:
  image: node:10
  stage: build
  script:
    - yarn install 
    - yarn build

  artifacts:
    expire_in: 1 week
    paths:
      - dist

unit test:
  image: node:10
  stage: test
  script:
    - yarn install 
    - npm run test

deploy:
  image: docker
  services:
    - docker:dind
  stages:
    - deploy
